In [2]:
import torch
import torch.nn as nn
import pandas as pd
import joblib

In [19]:
df = pd.read_csv(r"dataset/test.csv")

In [20]:
df.head(3)

       id     Sex  Age  Height  Weight  Duration  Heart_Rate  Body_Temp
0  750000    male   45   177.0    81.0       7.0        87.0       39.8
1  750001    male   26   200.0    97.0      20.0       101.0       40.5
2  750002  female   29   188.0    85.0      16.0       102.0       40.4

In [54]:
df_2 = pd.DataFrame({
    "id":1,
    "Sex":"male",
    "Age":36,
    "Height":189,
    "Weight":82,
    "Duration":26,
    "Heart_Rate":101,
    "Body_Temp":41.0
},index=[0])

In [55]:
df_2

   id   Sex  Age  Height  Weight  Duration  Heart_Rate  Body_Temp
0   1  male   36     189      82        26         101       41.0

In [56]:
onehotencoder = joblib.load('OneHotEncoder.pkl')
x_train_scaler = joblib.load("x_train_x_test.pkl")
y_train_scaler = joblib.load("y_train_y_test.pkl")

In [57]:
encoder = onehotencoder.transform(df_2[["Sex"]])

In [58]:
column_name_encoder = onehotencoder.get_feature_names_out()
column_name_encoder

array(['Sex_male'], dtype=object)

In [59]:
encoder_df = pd.DataFrame(encoder,columns=column_name_encoder)
encoder_df

   Sex_male
0       1.0

In [60]:
final_df = pd.concat(
    [df_2.drop("Sex",axis=1),encoder_df],axis=1
)

In [61]:
final_df

   id  Age  Height  Weight  Duration  Heart_Rate  Body_Temp  Sex_male
0   1   36     189      82        26         101       41.0       1.0

In [62]:
x = final_df.values

In [63]:
x_train_scaler = x_train_scaler.transform(x)

In [64]:
x_train = torch.tensor(x_train_scaler,dtype=torch.float32)

In [65]:
model = nn.Sequential(
    nn.Linear(8,128),
    nn.BatchNorm1d(128),
    nn.ReLU(),
    nn.Dropout(0.3),

    nn.Linear(128,64),
    nn.BatchNorm1d(64),
    nn.ReLU(),
    nn.Dropout(0.2),

    nn.Linear(64,32),
    nn.BatchNorm1d(32),
    nn.ReLU(),
    nn.Dropout(0.2),

    nn.Linear(32,1)
)

In [66]:
optimizer = torch.optim.Adam(model.parameters(),lr=0.01)

In [67]:
checkpoint = torch.load(
    r"Checkpoints_199.pth"
)

In [68]:
checkpoint

{'epochs': 199,
 'model': OrderedDict([('0.weight',
               tensor([[-0.1018, -0.2508, -0.0261,  ...,  0.2529,  0.0248, -0.1568],
                       [-0.0951, -0.0899, -0.2691,  ..., -0.0215,  0.0514,  0.1572],
                       [ 0.1896, -0.0839,  0.3034,  ..., -0.2331, -0.3378, -0.0800],
                       ...,
                       [ 0.2884, -0.3679,  0.3106,  ..., -0.1817, -0.2432,  0.1709],
                       [-0.1219, -0.2678,  0.1088,  ...,  0.0463,  0.1226, -0.0814],
                       [ 0.1454, -0.0678,  0.0723,  ...,  0.4513,  0.3182,  0.0077]])),
              ('0.bias',
               tensor([-0.1458,  0.1251, -0.1538, -0.1734,  0.2184,  0.1117,  0.2345,  0.2764,
                       -0.1836, -0.0100, -0.2883, -0.2933, -0.3149, -0.0022, -0.0704,  0.2733,
                       -0.2243, -0.2303,  0.2656,  0.1523, -0.0071, -0.0158,  0.1200,  0.0534,
                       -0.2386,  0.0858, -0.0827,  0.0265,  0.2163,  0.0912,  0.0694, -0.1523,
                       -0.1742, -0.2254,  0.2295, -0.0775, -0.3525, -0.0928, -0.0136,  0.2947,
                        0.1484,  0.0630,  0.0304,  0.1885,  0.3356, -0.3204, -0.0463,  0.2727,
                       -0.1362, -0.1800,  0.2588, -0.2235, -0.3182, -0.2457, -0.0262, -0.1579,
                        0.2949,  0.1686,  0.3154,  0.1982,  0.0335, -0.1672, -0.1728,  0.1457,
                       -0.2448, -0.0521, -0.1359,  0.0009, -0.3480,  0.0078, -0.2128,  0.1972,
                       -0.0925, -0.1350, -0.0328,  0.3126,  0.2345, -0.2741, -0.3522, -0.0786,
                       -0.3163,  0.3050,  0.3355, -0.2975, -0.0280,  0.1429,  0.2347,  0.3473,
                        0.0178, -0.3524,  0.0288,  0.1627, -0.1475, -0.3342, -0.2019, -0.2981,
                        0.1261,  0.2888,  0.1801, -0.3252,  0.3558, -0.2365,  0.2144,  0.0968,
                        0.1305,  0.2289, -0.0892, -0.3539, -0.2497, -0.0983,  0.2840,  0.1795,
                       -0.1394, -0.0216, -0.1215, -0.0253,  0.0371, -0.1664, -0.2749, -0.2964,
                        0.0928,  0.1443,  0.3482,  0.1166, -0.3165,  0.0518, -0.3161, -0.2355])),
              ('1.weight',
               tensor([0.9650, 0.9979, 1.0099, 0.9854, 0.9554, 1.0070, 0.9981, 0.9843, 0.9695,
                       0.9957, 0.9884, 0.9736, 1.0082, 0.9708, 1.0109, 1.0132, 0.9747, 0.9897,
                       1.0174, 0.9805, 0.9619, 0.9699, 0.9830, 0.9907, 1.0198, 1.0135, 1.0104,
                       0.9709, 0.9876, 0.9817, 1.0442, 1.0498, 1.0171, 1.0267, 1.0196, 0.9750,
                       0.9600, 1.0022, 0.9773, 1.0293, 1.0464, 1.0049, 0.9964, 0.9218, 0.9809,
                       0.9738, 1.0046, 0.9787, 0.9846, 0.9898, 1.0097, 1.0911, 0.9850, 1.0151,
                       1.0128, 1.0031, 0.9775, 1.0273, 1.0184, 0.9534, 1.0306, 1.0056, 0.9486,
                       0.9863, 0.9778, 1.0009, 0.9886, 1.0099, 0.9818, 0.9813, 0.9966, 1.0079,
                       1.0025, 1.0156, 0.9608, 0.9786, 1.0191, 0.9895, 0.9843, 1.0355, 0.9188,
                       0.9823, 0.9788, 0.9917, 1.0007, 1.0304, 0.9960, 1.0330, 0.9792, 1.0053,
                       0.9796, 0.9713, 0.9929, 0.9790, 0.9785, 1.0681, 0.9808, 1.0176, 0.9941,
                       1.0159, 1.0268, 1.0110, 1.0011, 0.9792, 1.0090, 0.9912, 0.9737, 0.9774,
                       0.9727, 1.0467, 0.9986, 1.0002, 1.0095, 1.0237, 1.0060, 0.9966, 0.9913,
                       1.0027, 0.9763, 0.9987, 0.9405, 0.9857, 1.0084, 0.9661, 1.0063, 0.9570,
                       0.9913, 0.9459])),
              ('1.bias',
               tensor([-0.0360,  0.0132,  0.0131, -0.0129, -0.0379,  0.0263,  0.0055, -0.0275,
                       -0.0272, -0.1135,  0.0399, -0.0822,  0.0251, -0.0343,  0.0805,  0.0203,
                       -0.0309, -0.0108, -0.0152, -0.0329, -0.0157, -0.0903, -0.0162,  0.0017,
                        0.0251,  0.0280,  0.0194, -0.0103, -0.0071, -0.0328,  0.0408, -0.0813,
                        0.0305, -0.1174,  0.0439, -0.0444, -0.0538, -0.0349, -0.0202, -0.1010,
                        0.0467, -0.0782, -0.0259, -0.0375, -0.0518, -0.0259,  0.0129, -0.0382,
                       -0.0673, -0.0125,  0.0657, -0.1035, -0.0273, -0.0664,  0.0199,  0.0006,
                       -0.0396,  0.0326,  0.0219, -0.0486, -0.0157, -0.0163, -0.0266,  0.0060,
                       -0.0123,  0.0021, -0.1036,  0.0161, -0.0191, -0.0238,  0.0171,  0.0070,
                       -0.0453, -0.0208, -0.0441, -0.0220, -0.0045, -0.0012, -0.0127, -0.0536,
                       -0.0456, -0.0201, -0.0755,  0.0034,  0.0098,  0.0049, -0.0488, -0.0601,
                       -0.0206,  0.0213, -0.0142, -0.0676, -0.0579, -0.0691, -0.0087,  0.0758,
                       -0.0267, -0.0225, -0.0249,  0.0234,  0.0492,  0.0421, -0.0324, -0.0383,
                        0.0289,  0.0272, -0.0291, -0.0252, -0.0253, -0.1188,  0.0655,  0.0449,
                       -0.0815,  0.0370, -0.0105,  0.0064, -0.0263, -0.0406,  0.0232, -0.0577,
                       -0.0400,  0.0104, -0.0046, -0.0248, -0.0076, -0.0339, -0.0111, -0.1259])),
              ('1.running_mean',
               tensor([-0.1457,  0.1252, -0.1538, -0.1734,  0.2184,  0.1117,  0.2346,  0.2764,
                       -0.1836, -0.0100, -0.2883, -0.2932, -0.3149, -0.0022, -0.0705,  0.2734,
                       -0.2244, -0.2303,  0.2656,  0.1523, -0.0071, -0.0159,  0.1200,  0.0533,
                       -0.2386,  0.0859, -0.0827,  0.0265,  0.2163,  0.0912,  0.0696, -0.1522,
                       -0.1742, -0.2255,  0.2295, -0.0774, -0.3524, -0.0927, -0.0136,  0.2947,
                        0.1484,  0.0631,  0.0304,  0.1885,  0.3356, -0.3205, -0.0464,  0.2727,
                       -0.1362, -0.1800,  0.2588, -0.2230, -0.3182, -0.2457, -0.0262, -0.1579,
                        0.2949,  0.1686,  0.3154,  0.1982,  0.0336, -0.1671, -0.1727,  0.1457,
                       -0.2448, -0.0521, -0.1359,  0.0009, -0.3480,  0.0078, -0.2128,  0.1972,
                       -0.0928, -0.1347, -0.0328,  0.3126,  0.2347, -0.2742, -0.3522, -0.0790,
                       -0.3164,  0.3050,  0.3356, -0.2974, -0.0280,  0.1430,  0.2347,  0.3472,
                        0.0178, -0.3524,  0.0288,  0.1628, -0.1475, -0.3341, -0.2019, -0.2981,
                        0.1261,  0.2889,  0.1800, -0.3252,  0.3557, -0.2365,  0.2144,  0.0968,
                        0.1305,  0.2289, -0.0892, -0.3539, -0.2497, -0.0981,  0.2840,  0.1795,
                       -0.1395, -0.0216, -0.1215, -0.0253,  0.0372, -0.1662, -0.2749, -0.2965,
                        0.0928,  0.1443,  0.3481,  0.1166, -0.3165,  0.0518, -0.3161, -0.2356])),
              ('1.running_var',
               tensor([0.0981, 0.0481, 0.2591, 0.3099, 0.2406, 0.9519, 0.0824, 0.6161, 0.2104,
                       0.1810, 0.3765, 0.2259, 0.3715, 0.0859, 0.2722, 0.3171, 0.3165, 0.4807,
                       0.0399, 0.6778, 0.4833, 0.1517, 0.1447, 0.0543, 0.5800, 0.1996, 0.5923,
                       0.6578, 0.4544, 0.3835, 0.0398, 0.3044, 0.8172, 0.1913, 0.3835, 0.2002,
                       0.1710, 0.3553, 0.2297, 0.2024, 0.1766, 0.1709, 0.1557, 0.8852, 0.2326,
                       0.1979, 0.1461, 0.1295, 0.2117, 0.3520, 0.4255, 0.0642, 0.2124, 0.3667,
                       0.0850, 0.1436, 0.4908, 0.0830, 0.3494, 0.3619, 0.5276, 0.1997, 0.2309,
                       0.3167, 0.2343, 0.0682, 0.1135, 0.4516, 0.3592, 0.1489, 0.1880, 0.3324,
                       0.0944, 0.3565, 0.0916, 0.1403, 0.5535, 0.5287, 0.1066, 0.3603, 0.3919,
                       0.3158, 0.0954, 0.2056, 0.1756, 0.2435, 0.1012, 0.2639, 0.1425, 0.2656,
                       0.0607, 0.5954, 0.2888, 0.2143, 0.5886, 0.3374, 0.4035, 0.1241, 0.2976,
                       0.3373, 0.0440, 0.7903, 0.6286, 0.2352, 0.3180, 0.4676, 0.0558, 0.3084,
                       0.4884, 0.2419, 0.2995, 0.5236, 0.7780, 0.7694, 0.4093, 0.3273, 0.4512,
                       0.2282, 0.0709, 0.6892, 0.6457, 0.3561, 0.2764, 0.4863, 1.1285, 0.6056,
                       0.3869, 0.4577])),
              ('1.num_batches_tracked', tensor(200)),
              ('4.weight',
               tensor([[ 0.0592,  0.0945,  0.0386,  ..., -0.0344,  0.0211, -0.0625],
                       [ 0.1056,  0.0840,  0.0869,  ..., -0.0605, -0.0264, -0.0333],
                       [-0.0212, -0.1012, -0.0384,  ..., -0.0324,  0.0281, -0.0157],
                       ...,
                       [-0.0352,  0.0143, -0.0560,  ...,  0.0231, -0.0766,  0.0069],
                       [ 0.0682,  0.0080,  0.0631,  ..., -0.0249, -0.0448, -0.0664],
                       [ 0.0245,  0.0549,  0.0102,  ..., -0.0564,  0.0172,  0.0399]])),
              ('4.bias',
               tensor([ 0.0357, -0.0623,  0.0121, -0.0821, -0.0396, -0.0378, -0.0097, -0.0403,
                       -0.0693,  0.0811,  0.0648, -0.0503, -0.0279, -0.0565, -0.0176, -0.0506,
                        0.0696, -0.0639, -0.0525, -0.0629,  0.0718,  0.0242,  0.0121, -0.0447,
                        0.0638,  0.0224, -0.0532, -0.0320,  0.0361, -0.0791, -0.0655, -0.0406,
                       -0.0330, -0.0690, -0.0062,  0.0290,  0.0652, -0.0801,  0.0113,  0.0645,
                       -0.0286, -0.0429,  0.0594, -0.0498, -0.0057, -0.0444,  0.0048, -0.0248,
                       -0.0927,  0.0159,  0.0547, -0.0281, -0.0768, -0.0006,  0.0292,  0.0947,
                        0.0173,  0.0653, -0.0793,  0.0261,  0.0407, -0.0503,  0.0039, -0.0488])),
              ('5.weight',
               tensor([0.9546, 0.9953, 1.0216, 1.0766, 1.0160, 0.9796, 1.0365, 0.9781, 1.0332,
                       0.9745, 1.0529, 0.9853, 0.9982, 1.0252, 0.9932, 0.9843, 1.0308, 0.9925,
                       0.9778, 0.9804, 0.9949, 0.9915, 0.9502, 0.9697, 0.9887, 0.9828, 0.9683,
                       0.9718, 1.0003, 0.9716, 0.9672, 1.0058, 0.9910, 1.0162, 1.0281, 0.9873,
                       1.0014, 0.9761, 1.0286, 1.0220, 0.9726, 0.9777, 0.9484, 0.9962, 0.9963,
                       0.9484, 1.0213, 0.9897, 1.0229, 0.9880, 0.9423, 0.9523, 1.0449, 0.9919,
                       0.9968, 0.9754, 0.9637, 1.0168, 1.1147, 1.0337, 1.0661, 1.0835, 0.9639,
                       1.0321])),
              ('5.bias',
               tensor([-0.0646, -0.0034,  0.0066, -0.0263,  0.0282, -0.0513,  0.0291, -0.0657,
                        0.0276, -0.0275,  0.0611, -0.0145, -0.0321,  0.0175, -0.1208, -0.0038,
                       -0.0210, -0.0087, -0.0950, -0.0147,  0.0102,  0.1090, -0.0877,  0.0144,
                        0.0244,  0.0125, -0.0667, -0.0232, -0.0721, -0.0548, -0.0579,  0.0045,
                        0.0004, -0.0010, -0.0026, -0.0145,  0.0124, -0.0403, -0.0079,  0.0267,
                       -0.0030, -0.0132, -0.1153,  0.0239, -0.1294, -0.0763, -0.0415,  0.0032,
                       -0.0110, -0.0380, -0.0976, -0.0464,  0.0570, -0.0391,  0.0587, -0.0060,
                       -0.1111, -0.0208,  0.0613,  0.0438,  0.0339,  0.0851, -0.0404,  0.0102])),
              ('5.running_mean',
               tensor([ 0.0351, -0.2859,  0.0716,  0.4363, -0.2950, -0.1142,  0.1222,  0.0519,
                        0.2368, -0.1580,  0.3058,  0.0031,  0.1015,  0.0045, -0.0110, -0.7066,
                        0.0776, -0.1260,  0.1983, -0.4788,  0.1042, -0.1486,  0.0773, -0.1459,
                        0.0391, -0.2047,  0.1053,  0.2477, -0.2374, -0.0757, -0.3041,  0.3466,
                        0.0082, -0.2424,  0.0038,  0.5618, -0.0692,  0.3006,  0.4354, -0.0145,
                        0.1887, -0.4617, -0.3854,  0.1570,  0.1621,  0.1026,  0.0773,  0.0510,
                        0.0937, -0.1828, -0.2621,  0.0782,  0.1456,  0.2337, -0.2779,  0.5060,
                        0.1817,  0.5088,  0.1928,  0.1595, -0.1283, -0.0311, -0.1583,  0.0032])),
              ('5.running_var',
               tensor([0.1009, 0.6419, 0.7669, 0.9276, 0.7553, 0.7314, 0.9308, 0.5179, 0.9505,
                       0.6216, 1.0298, 0.4185, 0.7138, 0.8015, 0.7567, 0.6423, 0.6584, 0.5330,
                       0.5952, 1.2239, 0.7755, 1.0329, 0.9613, 0.5932, 0.7868, 0.4483, 0.6024,
                       0.1821, 0.8102, 0.5788, 0.7144, 0.8053, 0.4753, 1.0620, 0.6314, 0.5888,
                       0.7095, 0.5382, 1.1503, 0.5940, 0.4560, 0.3774, 0.8138, 0.6283, 0.7113,
                       0.3077, 0.6996, 0.7018, 0.7390, 1.3547, 0.9381, 0.1994, 0.9714, 0.6571,
                       0.6305, 0.5155, 0.7646, 0.5693, 0.8606, 0.8329, 0.9923, 0.9571, 0.4269,
                       1.1961])),
              ('5.num_batches_tracked', tensor(200)),
              ('8.weight',
               tensor([[ 0.0228,  0.0242, -0.1536,  ...,  0.0894, -0.0518,  0.0991],
                       [-0.1253, -0.0442,  0.0810,  ..., -0.1003,  0.0778,  0.0191],
                       [-0.1340,  0.0541, -0.1422,  ...,  0.0549,  0.0856, -0.1436],
                       ...,
                       [ 0.0843,  0.0594, -0.0474,  ..., -0.0206, -0.0240, -0.1433],
                       [-0.1308,  0.0030, -0.1243,  ..., -0.0451,  0.1024, -0.1284],
                       [ 0.0589, -0.0221, -0.0663,  ..., -0.0350,  0.0994, -0.0523]])),
              ('8.bias',
               tensor([-0.0193,  0.0770, -0.1210,  0.0502, -0.0617,  0.0548, -0.0354, -0.0980,
                       -0.1001,  0.0711, -0.0194,  0.0567,  0.0742,  0.0618, -0.0688,  0.1069,
                        0.0095,  0.0150,  0.0017, -0.0841,  0.0143,  0.0686,  0.0639,  0.0961,
                        0.0278, -0.0459,  0.0301,  0.0422,  0.1104, -0.1261, -0.1077,  0.0435])),
              ('9.weight',
               tensor([0.9693, 0.9851, 0.9917, 0.9689, 0.9624, 1.0211, 0.9413, 0.9623, 0.9550,
                       0.9588, 0.9476, 1.0999, 0.9737, 0.9733, 0.9836, 0.9730, 0.9809, 0.9516,
                       0.9889, 0.9785, 0.9699, 1.0213, 1.0185, 0.9714, 0.9690, 0.9769, 0.9520,
                       0.9908, 1.0039, 0.9381, 0.9587, 0.9411])),
              ('9.bias',
               tensor([-0.0197, -0.0028,  0.0250, -0.0033, -0.0192,  0.0153, -0.0503, -0.0294,
                       -0.0645, -0.0318, -0.0496,  0.1027, -0.0207, -0.0065, -0.0123, -0.0169,
                       -0.0127, -0.0034, -0.0054, -0.0200, -0.0091,  0.0381,  0.0198, -0.0272,
                       -0.0210, -0.0110, -0.0393,  0.0050,  0.0055, -0.0634, -0.0337, -0.0346])),
              ('9.running_mean',
               tensor([-0.3541, -0.3527, -0.4463, -0.4269, -0.1401, -0.3596,  0.2308, -0.4017,
                       -0.4272, -0.3272, -0.2592, -0.1318, -0.0123, -0.2229, -0.3967,  0.0380,
                       -0.3342,  0.3337, -0.2609, -0.6586, -0.3497,  0.2165,  0.2777, -0.1852,
                       -0.1893, -0.1027, -0.1592, -0.1550, -0.5435, -0.2860, -0.5157,  0.1596])),
              ('9.running_var',
               tensor([1.0204, 1.0318, 0.7148, 0.5652, 1.3267, 0.9418, 0.1759, 0.3593, 0.7057,
                       0.6157, 0.7148, 0.7212, 0.2899, 1.4190, 0.5667, 0.8670, 0.4693, 0.5604,
                       0.6484, 0.7113, 0.6074, 0.6550, 0.7007, 0.5582, 0.8548, 0.7860, 0.5792,
                       1.0622, 0.9836, 0.6142, 0.7774, 0.4013])),
              ('9.num_batches_tracked', tensor(200)),
              ('12.weight',
               tensor([[-0.0692,  0.1092, -0.0449,  0.1064,  0.1327, -0.0339,  0.0417, -0.0399,
                        -0.1116, -0.0844, -0.0761,  0.0604, -0.0162,  0.1350, -0.0381,  0.1324,
                        -0.0441,  0.0941, -0.0457, -0.0690,  0.1237,  0.0670,  0.0680, -0.0442,
                        -0.0593, -0.0689, -0.0893,  0.1147, -0.0431, -0.0857, -0.0886,  0.0973]])),
              ('12.bias', tensor([-0.0722]))]),
 'optimizer_function': {'state': {0: {'step': tensor(200.),
    'exp_avg': tensor([[-6.8877e-05, -7.9180e-05, -2.0310e-05,  ...,  4.5345e-04,
              3.7748e-04, -6.2070e-05],
            [-3.9060e-04, -1.2623e-04, -1.1741e-04,  ..., -1.5695e-04,
             -2.7244e-04, -2.0368e-04],
            [ 2.6643e-04,  7.1265e-06,  1.6058e-04,  ...,  2.7872e-04,
              1.4501e-04,  1.5073e-04],
            ...,
            [ 2.6508e-06, -2.6470e-05, -9.3704e-06,  ..., -3.9573e-05,
              7.0171e-06, -1.1624e-05],
            [-1.3701e-04, -5.3555e-04,  1.3399e-04,  ..., -4.0078e-04,
             -9.8542e-05,  1.1667e-04],
            [-3.2245e-05, -3.0845e-04,  6.5100e-05,  ..., -2.5662e-04,
             -4.0843e-05,  1.6042e-05]]),
    'exp_avg_sq': tensor([[5.0745e-09, 1.1141e-07, 2.9534e-07,  ..., 9.2581e-06, 6.6038e-06,
             2.0272e-07],
            [5.0380e-07, 1.9965e-07, 2.0334e-06,  ..., 1.5161e-06, 1.6990e-06,
             3.5198e-06],
            [1.5304e-06, 3.9028e-07, 8.6306e-07,  ..., 1.3147e-06, 1.8306e-06,
             3.5068e-07],
            ...,
            [2.2628e-08, 7.6416e-08, 7.4443e-08,  ..., 8.0486e-07, 5.6870e-07,
             1.5160e-08],
            [7.6611e-08, 6.8763e-07, 1.2597e-07,  ..., 8.1920e-07, 2.0799e-07,
             5.3923e-08],
            [2.5198e-08, 2.9190e-07, 3.2277e-09,  ..., 2.9479e-07, 1.0149e-07,
             2.7108e-08]])},
   1: {'step': tensor(200.),
    'exp_avg': tensor([-4.7536e-11,  3.1666e-10, -1.3745e-11,  2.2613e-11,  2.8067e-11,
             7.9131e-12,  2.0376e-10,  2.6105e-11,  4.4385e-11,  4.2155e-11,
            -1.4250e-11, -5.5963e-11,  9.4191e-12, -8.4939e-11, -1.2685e-10,
            -2.9520e-12, -2.3002e-11,  2.1467e-11,  1.0782e-09, -2.2614e-11,
             2.1315e-11, -1.1019e-10, -3.9121e-11,  7.3953e-11, -7.8487e-12,
             6.0494e-11, -2.4631e-11,  1.8948e-11,  9.3921e-12, -4.3198e-11,
             2.7373e-11,  1.5598e-10, -1.3452e-11, -2.3990e-10,  7.0526e-11,
            -9.3798e-12,  8.1199e-11,  1.8014e-10,  1.9818e-12, -4.3071e-10,
             1.7507e-11, -2.3770e-10, -6.2494e-11, -3.2956e-12, -2.9979e-11,
            -8.7394e-12, -4.7014e-11,  2.0307e-10, -6.4439e-11,  1.6870e-11,
            -2.3554e-11,  6.9117e-10,  2.9027e-11,  6.7956e-11, -1.9656e-11,
             9.1687e-12,  5.7278e-12,  6.9413e-11,  4.5677e-11,  1.3963e-11,
             2.3101e-10,  1.6470e-10,  3.2375e-11, -3.2303e-11,  6.7184e-11,
            -1.5843e-11,  1.4830e-10, -1.0604e-11,  8.7616e-11, -2.2674e-11,
            -5.2947e-11, -1.5073e-11,  1.2597e-11,  4.9696e-11,  1.0713e-10,
             7.7152e-12,  1.8455e-10, -2.9117e-11,  8.2672e-11, -1.2502e-10,
            -8.8114e-11,  6.9791e-11, -2.2398e-10, -5.1141e-12, -2.6199e-12,
             2.4136e-10, -1.4985e-10,  4.8922e-11, -1.7295e-12, -2.7625e-11,
            -3.2154e-11,  1.4399e-11, -3.4088e-11,  2.3288e-10,  5.7113e-12,
             3.6771e-11, -7.5836e-11,  2.7563e-10, -1.8012e-10, -6.8422e-12,
            -9.0192e-13, -4.7353e-12,  8.6792e-11,  9.6480e-11, -1.5385e-12,
             2.4994e-11, -1.0740e-10,  2.4262e-11,  5.8013e-12,  3.2955e-10,
            -7.6613e-11, -6.6277e-12, -9.8318e-11,  6.4179e-12,  6.3395e-12,
            -4.0865e-13,  1.1187e-10,  3.2959e-10, -1.6267e-10, -1.0137e-10,
             4.2933e-12,  4.7684e-12, -1.1639e-10, -4.7161e-12, -9.9354e-12,
             2.5810e-11,  7.1577e-12, -1.2794e-10]),
    'exp_avg_sq': tensor([3.0348e-18, 2.7124e-18, 1.7576e-17, 4.9851e-18, 5.8758e-19, 2.9487e-19,
            3.0196e-16, 1.9931e-18, 1.9002e-18, 6.4618e-19, 3.8530e-19, 6.8975e-19,
            1.7402e-18, 6.3638e-19, 3.9311e-19, 1.8843e-17, 1.3703e-18, 1.7550e-17,
            1.8633e-16, 7.4489e-21, 9.5127e-20, 1.3145e-19, 3.2630e-18, 4.2679e-19,
            1.3449e-17, 1.8403e-17, 1.1602e-18, 5.8502e-20, 2.8587e-19, 4.4481e-19,
            6.8082e-19, 6.1679e-19, 2.7969e-19, 2.9453e-19, 2.6272e-18, 5.9690e-20,
            3.6051e-19, 5.1693e-18, 5.5783e-19, 6.1159e-19, 2.3205e-18, 1.5874e-18,
            2.0023e-18, 1.8575e-20, 2.6029e-19, 7.0394e-18, 7.8376e-19, 5.6193e-18,
            8.8127e-19, 2.5699e-19, 3.3334e-19, 8.8379e-18, 1.7444e-18, 1.8545e-19,
            3.6267e-18, 1.7064e-19, 2.2487e-19, 1.2999e-17, 3.0076e-17, 1.1147e-19,

In [69]:
model.load_state_dict(checkpoint["model"])

In [70]:
optimizer.load_state_dict(checkpoint["optimizer_function"])

In [71]:
optimizer

Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    decoupled_weight_decay: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.001
    maximize: False
    weight_decay: 0
)

In [72]:
epochs = checkpoint["epochs"]

In [73]:
epochs

199

In [74]:
loss = checkpoint["loss"]

In [75]:
loss

0.0555766262114048

In [76]:
model.eval()

Sequential(
  (0): Linear(in_features=8, out_features=128, bias=True)
  (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, bias=True, track_running_stats=True)
  (2): ReLU()
  (3): Dropout(p=0.3, inplace=False)
  (4): Linear(in_features=128, out_features=64, bias=True)
  (5): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, bias=True, track_running_stats=True)
  (6): ReLU()
  (7): Dropout(p=0.2, inplace=False)
  (8): Linear(in_features=64, out_features=32, bias=True)
  (9): BatchNorm1d(32, eps=1e-05, momentum=0.1, affine=True, bias=True, track_running_stats=True)
  (10): ReLU()
  (11): Dropout(p=0.2, inplace=False)
  (12): Linear(in_features=32, out_features=1, bias=True)
)

In [77]:
with torch.no_grad():
    pred = model(x_train)

pred = y_train_scaler.inverse_transform(pred)

In [81]:
int(pred.round())

/tmp/ipykernel_3548/715960600.py:1: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  int(pred.round())

144